Improve "not found" error message (#121) (#122)
The current message:

```
The following image references were not found: [eu.gcr.io/robco-rodrigoq/move-endpoint:latest]
```

suggests to the untrained eye that they should check that image has not
been found on the container registry, as the user may not know that the
resolver is replacing image references inside the YAML file.

This commit changes the message to:

```
ERROR: The following image references were not found in '/your/bazel/cache/dir/execroot/__main__bazel-out/k8-opt/bin/your/package/path/k8s.runfiles/__main__/your/package/path/deployment.yaml':
    eu.gcr.io/robco-rodrigoq/move-endpoint:latest
```

which is very long but hopefully clearer, as the user can look at that
file to work out why the image reference is not found.